export const AI_GUIDE_SCHEMA_VERSION = 1 as const;

export function renderAiGuideText() {
  return [
    "# GUIA DE GERAÇÃO E EDIÇÃO DE ROTEIROS — NYMI GACHA",
    "",
    `Versão do guia: ${AI_GUIDE_SCHEMA_VERSION}`,
    "Este documento é um guia reutilizável. Ele não contém fichas, vídeos ou dados de um roteiro específico.",
    "Use este guia junto do arquivo EXECUTE_E_GERE_JSON_<ROTEIRO>.md quando precisar gerar uma base pronta.",
    "",
    "## OBJETIVO",
    "Gerar falas e pensamentos em português brasileiro para personagens reagindo às cenas de vídeos, respeitando personalidade, regras, duração e continuidade.",
    "",
    "## TIPOS DE BLOCO",
    "- speech: fala audível do personagem.",
    "- thought: pensamento do personagem; não é audível.",
    "- Não use reaction type silent. Pensamentos devem usar thought.",
    "- Todo bloco precisa de characterId, type, emotion e text.",
    "",
    "## DURAÇÃO E QUANTIDADE",
    "- reactionStartSeconds é o momento em que começam falas e pensamentos.",
    "- reactionWindowSeconds é a duração do vídeo menos reactionStartSeconds.",
    "- Use recommendedBlockCount como alvo, não gere muitos blocos desnecessários.",
    "- A faixa recomendada é uma orientação: normalmente use entre min e max.",
    "- Continuação depois do vídeo é permitida quando a fala precisar terminar, mas não justifica criar uma sequência longa.",
    "- Se duração ou início não estiverem definidos, use a descrição e escolha poucos blocos.",
    "",
    "## REGRAS DE CONTEXTO",
    "- Use somente os dados do roteiro presente na base anexada.",
    "- Não misture descrições, fichas ou vídeos de outros roteiros.",
    "- Não invente personagens, vídeos, IDs ou acontecimentos fora do contexto.",
    "- Preserve a personalidade, relações, estilo de fala e regras particulares.",
    "- Não repita a ficha do personagem dentro das falas.",
    "",
    "## FALAS EM DOIS IDIOMAS",
    "- text deve ser português brasileiro.",
    "- englishText deve ser a tradução correspondente quando o contrato pedir inglês.",
    "- Não crie uma fala em inglês com conteúdo diferente do português.",
    "",
    "## ORDEM DOS TIKTOKS",
    "A base pode permitir uma proposta de ordem editorial. Sempre use sectionId, nunca o número visual do TikTok como identificador.",
    "A abertura permanece antes dos TikToks. Não remova, duplique ou recrie seções.",
    "Quando houver orderingProposal, preserve todos os IDs exatamente uma vez e explique o motivo de cada mudança.",
    "",
    "## FORMATO DE RESPOSTA",
    "Retorne somente JSON válido no arquivo RESPOSTA_<scriptId>.json.",
    "Preserve sourceScriptId, sectionId, characterId e blockId quando um bloco existente for referenciado.",
    "Blocos manuais preenchidos devem ser preservados pelo aplicativo.",
    "",
    "### EXEMPLO DE BLOCO",
    "```json",
    JSON.stringify({ blockId: null, characterId: "id-do-personagem", type: "speech", emotion: "surpreso", text: "Isso aconteceu mesmo?", englishText: "Did that really happen?" }, null, 2),
    "```",
    "",
    "### EXEMPLO DE PROPOSTA DE ORDEM",
    "```json",
    JSON.stringify({ orderingProposal: { mode: "suggest", orderedSectionIds: ["tiktok-1-id", "tiktok-4-id", "tiktok-2-id"], changes: [{ sectionId: "tiktok-4-id", fromPosition: 4, toPosition: 2, reason: "Melhora a progressão do conflito." }] } }, null, 2),
    "```",
    "",
    "## COMPORTAMENTO ESPERADO",
    "Execute a tarefa ao receber a base. Não responda apenas com um plano e não peça confirmação antes de analisar o conteúdo. Gere o JSON final conforme o contrato da base.",
    "",
  ].join("\n");
}
