/** Adaptador público temporário; contratos canônicos vivem em app/domain. */
export type {
  AiCharacterContext,
  AiProvider,
  GeneratedReaction,
  GlobalRule,
  OpeningSection,
  NarrativeProfile,
  NarrativeRelationship,
  PremiumCharacter,
  ReactionBlock,
  ReactionBlockType,
  RoteirosSettings,
  RoteirosState,
  RoteiroExportTarget,
  RulePriority,
  SaveStatus,
  ScriptParticipant,
  ScriptProject,
  TikTokSection,
  TikTokTimeline,
  TikTokVideoReference,
} from "../domain/roteiro-contract";
