import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

test("a nova Base de dados possui o layout e os controles básicos independentes", async () => {
  const page = await readFile(new URL("../app/base de dados/BaseDadosPage.tsx", import.meta.url), "utf8");
  const styles = await readFile(new URL("../app/base de dados/base-de-dados.module.css", import.meta.url), "utf8");
  const shell = await readFile(new URL("../app/shared/NymiShell.tsx", import.meta.url), "utf8");
  const storage = await readFile(new URL("../app/base de dados/storage.ts", import.meta.url), "utf8");
  assert.match(page, /Pacote completo para IA/);
  assert.match(page, /Exportar dados simples/);
  assert.match(page, /Importar roteiro da IA/);
  assert.doesNotMatch(page, /exportGuide/);
  assert.doesNotMatch(page, /onClick=\{exportData\}/);
  assert.match(page, /Descrição do que acontece no vídeo/);
  assert.match(page, /Fim da cena de descrição/);
  assert.match(page, /captureVideoTime\(video\.id, "sceneEndSeconds"\)/);
  assert.match(page, /Quantidade de falas/);
  assert.match(page, /firstGroupReactionSpeechCount/);
  assert.match(page, /secondGroupReactionSpeechCount/);
  assert.match(styles, /\.reactionPanel/);
  assert.match(page, /uploadBaseDadosVideo/);
  assert.match(page, /removeBaseDadosVideo/);
  assert.match(page, /baseDadosVideoUrl/);
  assert.match(page, /preload="metadata"/);
  assert.doesNotMatch(page, /preload="auto"/);
  assert.match(page, /function persistSelectedCharacterIds/);
  assert.match(page, /Buscar cenas/);
  assert.match(page, /Filtros/);
  assert.match(page, /visibleVideos/);
  assert.match(styles, /\.pageHeader/);
  assert.match(styles, /grid-template-columns:repeat\(2,minmax\(0,520px\)\)/);
  assert.match(page, /captureVideoTime\(video\.id, "firstGroupReactionSeconds"\)/);
  assert.match(page, /captureVideoTime\(video\.id, "secondGroupReactionSeconds"\)/);
  assert.match(styles, /\.player video/);
  assert.match(storage, /\/base-dados\/videos/);
  assert.match(shell, /Base de dados/);
});
