import Link from "next/link";
import { ToolsTopbar } from "./components/ToolsTopbar";
import styles from "./ferramentas.module.css";

export default function FerramentasPage() {
  return <div className={styles.page}><ToolsTopbar title="Ferramentas" subtitle="Utilitários para o seu fluxo de criação" backHref="/" brandLabel="Voltar para Personagens" /><main className={`${styles.main} ${styles.dashboardMain}`}>
    <div className={styles.breadcrumb}><span>Workspace</span><b>/</b><strong>Ferramentas</strong></div>
    <section className={`${styles.hero} ${styles.dashboardHero}`}><div><span className={styles.eyebrow}>Área independente</span><h1>Ferramentas</h1><p>Um espaço organizado para preparar assets e acelerar a produção sem misturar as ferramentas ao fluxo principal.</p></div><div className={styles.heroStat}><strong>05</strong><span>ferramentas disponíveis</span></div></section>
    <section className={styles.sectionIntro}><div><span className={styles.sectionLabel}>Seu workspace</span><h2>Escolha uma ferramenta</h2><p>Entre direto no utilitário que você precisa agora.</p></div><span className={styles.availability}><i /> Operacional</span></section>
    <section className={styles.grid}>
      <Link className={styles.toolCard} href="/Ferramentas/green-bg-pro"><div className={styles.toolCardTop}><span className={styles.toolIcon} aria-hidden="true">✦</span><span className={styles.toolStatus}>Disponível</span></div><div className={styles.toolCardBody}><h2>Green BG PRO</h2><p>Remova fundos verdes com controles de tolerância, proteção, feather e despill para preparar seus assets.</p></div><div className={styles.toolCardFooter}><span>Recorte inteligente · PNG transparente</span><span className={styles.toolArrow}>Abrir <b>→</b></span></div></Link>
      <Link className={styles.toolCard} href="/Ferramentas/alinhador-profissa"><div className={styles.toolCardTop}><span className={styles.toolIcon} aria-hidden="true">⌖</span><span className={styles.toolStatus}>Disponível</span></div><div className={styles.toolCardBody}><h2>Alinhador Profissa</h2><p>Estabilize folhas de cabeças, compare expressões e prepare modelos canônicos com calibração visual.</p></div><div className={styles.toolCardFooter}><span>Folhas de expressão · calibração</span><span className={styles.toolArrow}>Abrir <b>→</b></span></div></Link>
      <Link className={styles.toolCard} href="/Ferramentas/alinhador-profissional-v2"><div className={styles.toolCardTop}><span className={styles.toolIcon} aria-hidden="true">◎</span><span className={styles.toolStatus}>V2 experimental</span></div><div className={styles.toolCardBody}><h2>Alinhador Profissional V2</h2><p>Ambiente independente para alinhar landmarks, comparar silhuetas e corrigir deformações locais sem alterar os originais.</p></div><div className={styles.toolCardFooter}><span>Landmarks · warp regional · comparação</span><span className={styles.toolArrow}>Abrir <b>→</b></span></div></Link>
      <Link className={styles.toolCard} href="/Ferramentas/laboratorio-cor-modelo"><div className={styles.toolCardTop}><span className={styles.toolIcon} aria-hidden="true">◉</span><span className={styles.toolStatus}>Laboratório</span></div><div className={styles.toolCardBody}><h2>Laboratório de Cor</h2><p>Crie e revise máscaras independentes para recolorir pupilas e sobrancelhas sem atingir boca, blush, pele ou contornos.</p></div><div className={styles.toolCardFooter}><span>Segmentação assistida · comparação</span><span className={styles.toolArrow}>Abrir <b>→</b></span></div></Link>
      <Link className={styles.toolCard} href="/Ferramentas/teste-controles-cor"><div className={styles.toolCardTop}><span className={styles.toolIcon} aria-hidden="true">◌</span><span className={styles.toolStatus}>Teste isolado</span></div><div className={styles.toolCardBody}><h2>Teste de Controles de Cor</h2><p>Teste a mesma recoloração do Criador diretamente nos modelos e expressões, sem alterar personagens ou arquivos.</p></div><div className={styles.toolCardFooter}><span>Mesmo compositor · diagnóstico visual</span><span className={styles.toolArrow}>Abrir <b>→</b></span></div></Link>
    </section>
    <section className={styles.flowPanel}><div className={styles.flowHeading}><span className={styles.sectionLabel}>Fluxo rápido</span><h2>Da folha ao catálogo</h2></div><div className={styles.flowSteps}><div><span>01</span><strong>Importe</strong><small>Folha 1 e extensão opcional</small></div><div><span>02</span><strong>Revise</strong><small>Compare, calibre e marque rostos</small></div><div><span>03</span><strong>Salve</strong><small>Modelo disponível no Criador</small></div></div></section>
  </main></div>;
}
