import Link from "next/link";
import { ToolsTopbar } from "./components/ToolsTopbar";
import styles from "./ferramentas.module.css";

export default function FerramentasPage() {
  return <div className={styles.page}><ToolsTopbar title="Ferramentas" subtitle="Utilitários para o seu fluxo de criação" backHref="/" brandLabel="Voltar para Personagens" /><main className={`${styles.main} ${styles.dashboardMain}`}>
    <div className={styles.breadcrumb}><span>Workspace</span><b>/</b><strong>Ferramentas</strong></div>
    <section className={`${styles.hero} ${styles.dashboardHero}`}><div><span className={styles.eyebrow}>Área independente</span><h1>Ferramentas</h1><p>Um espaço organizado para preparar assets e acelerar a produção sem misturar as ferramentas ao fluxo principal.</p></div><div className={styles.heroStat}><strong>04</strong><span>ferramentas disponíveis</span></div></section>
    <section className={styles.sectionIntro}><div><span className={styles.sectionLabel}>Seu workspace</span><h2>Escolha uma ferramenta</h2><p>Entre direto no utilitário que você precisa agora.</p></div><span className={styles.availability}><i /> Operacional</span></section>
    <section className={styles.grid}>
      <Link className={styles.toolCard} href="/Ferramentas/green-bg-pro"><div className={styles.toolCardTop}><span className={styles.toolIcon} aria-hidden="true">✦</span><span className={styles.toolStatus}>Disponível</span></div><div className={styles.toolCardBody}><h2>Green BG PRO</h2><p>Remova fundos verdes com controles de tolerância, proteção, feather e despill para preparar seus assets.</p></div><div className={styles.toolCardFooter}><span>Recorte inteligente · PNG transparente</span><span className={styles.toolArrow}>Abrir <b>→</b></span></div></Link>
      <Link className={styles.toolCard} href="/Ferramentas/alinhador-profissa"><div className={styles.toolCardTop}><span className={styles.toolIcon} aria-hidden="true">⌖</span><span className={styles.toolStatus}>Disponível</span></div><div className={styles.toolCardBody}><h2>Alinhador Profissa</h2><p>Estabilize folhas de cabeças, compare expressões e prepare modelos canônicos com calibração visual.</p></div><div className={styles.toolCardFooter}><span>Folhas de expressão · calibração</span><span className={styles.toolArrow}>Abrir <b>→</b></span></div></Link>
      <Link className={styles.toolCard} href="/Ferramentas/area2-final-head-lock"><div className={styles.toolCardTop}><span className={styles.toolIcon} aria-hidden="true">⛓</span><span className={styles.toolStatus}>Disponível</span></div><div className={styles.toolCardBody}><h2>PROCESSADOR V2</h2><p>Trave a posição das cabeças, corrija revisões e compare contornos com processamento independente.</p></div><div className={styles.toolCardFooter}><span>Head Lock · revisão · exportação ZIP</span><span className={styles.toolArrow}>Abrir <b>→</b></span></div></Link>
      <Link className={styles.toolCard} href="/Ferramentas/fabricador-de-modelo"><div className={styles.toolCardTop}><span className={styles.toolIcon} aria-hidden="true">◉</span><span className={styles.toolStatus}>Beta</span></div><div className={styles.toolCardBody}><h2>Fabricador de Modelo</h2><p>Encaixe uma folha de olhos no molde fixo, revise o par aberto/fechado e gere 21 expressões derivadas.</p></div><div className={styles.toolCardFooter}><span>Olhos · chroma · expressões</span><span className={styles.toolArrow}>Abrir <b>→</b></span></div></Link>
    </section>
    <section className={styles.flowPanel}><div className={styles.flowHeading}><span className={styles.sectionLabel}>Fluxo rápido</span><h2>Da folha ao catálogo</h2></div><div className={styles.flowSteps}><div><span>01</span><strong>Importe</strong><small>Folha 1 e extensão opcional</small></div><div><span>02</span><strong>Revise</strong><small>Compare, calibre e marque rostos</small></div><div><span>03</span><strong>Salve</strong><small>Modelo disponível no Criador</small></div></div></section>
  </main></div>;
}
