export const EYE_EXPRESSIONS = [
  ["aliviada", "Aliviada"], ["animada", "Animada"], ["apaixonada", "Apaixonada"],
  ["cansada", "Cansada"], ["ciumenta", "Ciumenta"], ["confusa", "Confusa"],
  ["decepcionada", "Decepcionada"], ["desconfiada", "Desconfiada"], ["envergonhada", "Envergonhada"],
  ["impressionada", "Impressionada"], ["indignada", "Indignada"], ["irritada", "Irritada"],
  ["nojo", "Nojo"], ["normal", "Normal"], ["orgulhosa", "Orgulhosa"],
  ["preocupada", "Preocupada"], ["seria", "Séria"], ["sorrindo_de_canto", "Sorrindo de canto"],
  ["sorriso_maligno", "Sorriso maligno"], ["surpresa", "Surpresa"], ["triste_magoada", "Triste/magoada"],
] as const;

export const EXPRESSION_VARIATIONS = [
  { scaleX: 1, scaleY: 1, rotation: 0, x: 0, y: 0 },
  { scaleX: .92, scaleY: 1.06, rotation: 0, x: 0, y: 1 },
  { scaleX: 1.08, scaleY: .92, rotation: -1.5, x: -1, y: 0 },
  { scaleX: .9, scaleY: 1.12, rotation: 1.5, x: 1, y: -1 },
  { scaleX: .84, scaleY: 1.16, rotation: -2, x: 0, y: -1 },
  { scaleX: 1.03, scaleY: .86, rotation: 0, x: 0, y: 1 },
  { scaleX: .96, scaleY: .82, rotation: 2, x: 1, y: 1 },
  { scaleX: 1.1, scaleY: .88, rotation: -2, x: -1, y: 1 },
  { scaleX: 1.14, scaleY: .8, rotation: 1, x: 0, y: 1 },
  { scaleX: .88, scaleY: .98, rotation: -3, x: -1, y: 0 },
  { scaleX: 1.16, scaleY: .9, rotation: 3, x: 1, y: 0 },
  { scaleX: 1.1, scaleY: 1.12, rotation: 0, x: 0, y: -2 },
  { scaleX: 1.18, scaleY: 1.16, rotation: 0, x: 0, y: -2 },
  { scaleX: .94, scaleY: .7, rotation: 0, x: 0, y: 2 },
  { scaleX: .88, scaleY: .9, rotation: 5, x: 2, y: 0 },
  { scaleX: .86, scaleY: .86, rotation: -4, x: -2, y: 1 },
  { scaleX: .96, scaleY: .96, rotation: -2, x: 0, y: 0 },
  { scaleX: 1.2, scaleY: 1.05, rotation: 0, x: 0, y: -1 },
  { scaleX: .9, scaleY: .8, rotation: 2, x: 0, y: 2 },
  { scaleX: .95, scaleY: .9, rotation: -7, x: -4, y: 0 },
  { scaleX: 1.04, scaleY: 1.04, rotation: 4, x: 2, y: -1 },
] as const;
