export type SheetId = "primary" | "extension";
export type ExpressionState = "default" | "blink" | "talk";
export type ChromaColor = { r: number; g: number; b: number };
export type FaceRegion = { x: number; y: number; width: number; height: number; row: number; column: number };
export type StructuralProfilePoint = { y: number; widthNorm: number; centerOffset: number };
export type FaceAnatomy = {
  width: number;
  height: number;
  centerX: number;
  centerY: number;
  structuralTop: number;
  structuralBottom: number;
  neckCenterX: number;
  neckWidth: number;
  neckBaseY: number;
  cranialWidth: number;
  profile: StructuralProfilePoint[];
  structuralBounds: { x: number; y: number; width: number; height: number };
  visualBounds: { x: number; y: number; width: number; height: number };
};
export type SpriteAdjustment = { scale: number; scaleX: number; scaleY: number; dx: number; dy: number; reviewed: boolean };
export type QualityMetrics = {
  overall: number;
  stability: number;
  scale: number;
  position: number;
  proportion: number;
  shape: number;
  neck: number;
  compatibility?: number;
  critical: boolean;
  warning: boolean;
  reasons: string[];
};
export type CalibrationSettings = {
  baseScale: number;
  primaryStrength: number;
  primaryMaxCorrection: number;
  extensionMaxCorrection: number;
  extensionMicroAdjustment: number;
  structuralAlignment: boolean;
  preserveExpressiveDetails: boolean;
  tolerance: number;
  softness: number;
  feather: number;
  despill: number;
  cleanEdges: boolean;
  contentPadding: number;
  squareCrop: boolean;
  tightCrop: boolean;
  anchorX: number;
  anchorY: number;
};
export type GeneratedSprite = {
  key: string;
  sourceSheet: SheetId;
  state: ExpressionState;
  dataUrl: string;
  width: number;
  height: number;
  anatomy: FaceAnatomy;
  adjustment: SpriteAdjustment;
  quality: QualityMetrics;
};
export type ModelExpression = { key: string; sourceSheet: SheetId; default: GeneratedSprite; blink: GeneratedSprite; talk: GeneratedSprite };
export type HeadMaster = {
  width: number;
  height: number;
  centerX: number;
  neckCenterX: number;
  neckWidth: number;
  neckBaseY: number;
  structuralLeft: number;
  structuralRight: number;
  structuralBottom: number;
  structuralWidth: number;
  profile: StructuralProfilePoint[];
  usableIndices: number[];
  outlierIndices: number[];
  referenceIndex: number;
  bestTrioColumn: number;
  stabilityScore: number;
};
export type CompatibilityMetrics = { size: number; proportion: number; silhouette: number; jaw: number; neck: number; overall: number; status: string };
export type ModelSettings = { name: string; folderName: string; gender: "feminino" | "masculino"; anchorX: number; anchorY: number };
export type SheetResult = {
  id: SheetId;
  fileName: string;
  width: number;
  height: number;
  regions: FaceRegion[];
  expressions: ModelExpression[];
  imageUrl: string;
  headMaster: HeadMaster;
  compatibility?: CompatibilityMetrics;
};
export type ModelValidation = { errors: string[]; warnings: string[]; critical: number };
